export const faqs = [
    {
        pergunta: "Como indentificar se um cliente é banco modelo ou banco em uso?",
        resposta: "Para definir se o banco será “modelo” ou “em uso”, siga o seguinte passo a passo:<ol><li>Vá ao SGD e pesquise pelo nome do licenciado:</li><img src='../../images/duvidas-frequentes/Como indentificar se um cliente é banco modelo ou banco em uso/pesquisa_cliente_sgd.png' alt='pesquisa_cliente_sgd'></img><br><li>Depois avalie a opção “SSC’s Pendentes”, caso haja alguma SSC provavelmente esse será um <u>banco em uso</u>. Mas caso não haja nenhuma solicitação de suporte, provavelmente será um <u>banco modelo</u>.<br></li><img src='../../images/duvidas-frequentes/Como indentificar se um cliente é banco modelo ou banco em uso/analise_pendencias.png' alt='analise_pendencias'></img><br><li>Avalie também na opção “Detalhes”, desde de quando esse licenciado utiliza os serviços da Domínio, se for um cliente mais recente ele será <u>banco modelo</u>, mas caso seja um cliente mais antigo ele será <u>banco em uso</u></li><img src='../../images/duvidas-frequentes/Como indentificar se um cliente é banco modelo ou banco em uso/cliente_desde.png' alt='cliente_desde'></img><br><li>Caso ainda possua dúvida sobre o tipo de banco que esse cliente será, vá em “Implantações” (que fica ao final da página de detalhes) e veja como está a situação desse cliente.</li><ul><li>Não iniciado</li><li>Em Andamento</li><li>Concluído</li></ul><img src='../../images/duvidas-frequentes/Como indentificar se um cliente é banco modelo ou banco em uso/olhar_implantacao.png' alt='olhar_implantacao'></img></ol>"
    },
    {
      pergunta: "Quais as diferenças de um cliente com Backup em Nuvem e um cliente DW?",
      resposta: "<p>Primeiro, é importante extabelecer 2 conceitos importates:</p><li><b>Banco de produção:</b> São os arquivos contabil.db + contabil.log, o banco de produção é a base de dados que o cliente utiliza diariamente e realiza todas as suas movimentações, atualizações, consultas, etc.</li><li><b>Backup:</b> Os backups, são cópias de segurança do banco de produção. Por serem apenas cópias elas podem ser amarzenadas em diversos lugares diferentes, como localmente em um arquivo de armazenamento ou em um servidor em nuvem.</li><hr><h2>Backup em Nuvem:</h2><p>O backup em nuvem é utilizado por clientes que possuem o seu banco de produção <b>local</b>, porém salvam as suas cópias de segurança (backup) em um servidor da AWS. O serviço de Backup em Nuvem pode ser adiquirido a parte por clientes Domíno Start e Plus, no pacote Domínio Premium o backup em Nuvem já vem incluso.<p><h2>Domínio Web</h2><p>Quando o cliente utiliza o Domínio Web, tanto o seu banco de produção quando os backups estão armazenados em servidores da AWS, ou seja, o cliente não possui localmente nas máquinas do escritorio os arquivos referente ao banco de dados e backups.Para termos acesso aos backup, é preciso que o cliente libere o acesso a eles. Para termos acesso ao banco de produção, é necessário solicitar via SS para a matriz, para que ele seja disponibilizado. Somente a matriz tem acesso aos servidores da AWS para realizar alterações e manipulações.</p><img src='../../images/duvidas-frequentes/Quais as diferenças de um cliente com Backup em Nuvem e um cliente DW/Exemplo_cliente_backup_em_nuvem.png' alt='Exemplo_cliente_backup_em_nuvem'>Exemplo cliente Backup em nuvem</img><img src='../../images/duvidas-frequentes/Quais as diferenças de um cliente com Backup em Nuvem e um cliente DW/Exemplo_cliente_DW.png' alt='Exemplo_cliente_DW'>Exemplo cliente com Domínio Web</img><img src='../../images/duvidas-frequentes/Quais as diferenças de um cliente com Backup em Nuvem e um cliente DW/Exemplo_cliente_premiun.png' alt='Exemplo_cliente_premiun'>Exemplo cliente Domínio Premium</img>"
    },
    {
      pergunta: "Como saber quem deverá fazer a substituição nos processo de banco em uso?",
      resposta: "<p>Para saber quem fará a substituição da base dados em processos de Banco em Uso, basta apenas observar o seguinte ponto:</p><li><b>Base Dominio Local: </b> Substituição será feita pelo time de Q.A.</li><li><b>Base Domínio Web: </b> Substituição será feita pelo desenvolvedor</li>"
    }
  ]